# First steps into Pytorch
for more details: https://pytorch.org/docs/stable/index.html

In [2]:
#Let's start by importing the library
import torch

A <code>torch.Tensor</code> is a multi-dimensional matrix containing elements of a single data type.

In [3]:
# Generate a Tensor of size 2x2x4
t = torch.Tensor(2,2,4)
# .size() allows to get the size of the tensor
print(t.size())

torch.Size([2, 2, 4])


In [4]:
# Generate a tensor filled with random numbers 
# from a normal distribution with mean 0 and variance 1 
# with the same size
t_r = torch.randn(2,2,4)
# and a tensor filled with ones
t_ones = torch.ones(2,2,4)

In [5]:
# Print the tensors
print(t, t_r, t_ones)

tensor([[[4.7562e+30, 9.2860e-04, 1.1867e+27, 1.7860e+25],
         [2.8930e+12, 7.5338e+28, 3.1992e-12, 2.6209e+20]],

        [[2.0530e-19, 1.1432e+27, 1.0903e+27, 1.4603e-19],
         [1.2102e+25, 1.1839e+22, 7.0976e+22, 5.7886e+22]]]) tensor([[[-0.6815,  2.6807,  0.8325,  1.5781],
         [ 1.0567, -0.2898, -0.2333,  0.9495]],

        [[-0.6384,  0.8587,  0.9984,  0.1470],
         [ 0.8431, -0.2119, -0.5255,  1.4200]]]) tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [6]:
# To resize a tensor do
t.resize_(4,4)
print(t.size())
# be CAREFULL with in-place operations like this one
# since they will permanently change the tensor

torch.Size([4, 4])


In [7]:
# It is better to firstly clone the tensor and then resize it
t_c = t.clone()
t_c.resize_(2,2)
# so that the original one remains untouched
print(t.size(), t_c.size())

torch.Size([4, 4]) torch.Size([2, 2])


In [8]:
# Fill a tensor with a specific number
t_ones.fill_(3)
print(t_ones)

tensor([[[3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[3., 3., 3., 3.],
         [3., 3., 3., 3.]]])


In [9]:
# If you want to create a tensor filled with specific numbers just do
v = torch.Tensor([7,8,9])
print(v)

tensor([7., 8., 9.])


Working with tensors is exactly like working with vectors and matrices!

In [10]:
w = torch.Tensor([3,2,1]) # a vector
# Sum (or subtraction)
print(w + v)
# Element-wise multiplication (or division)
print(w * v)
# Square all elements in the tensor
w2 = w.pow(2)
# and so on...

tensor([10., 10., 10.])
tensor([21., 16.,  9.])


In [11]:
# Define a 2x4 matrix
m = torch.Tensor([[1,2,3,4],
                 [5,6,7,8]])
print(m)
print(m.size(), m.size(0), m.size(1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4]) 2 4


In [12]:
# Get a value from the matrix
print(m[1,2])
# Get a column
print(m[:,2])
# Get a row
print(m[1, :])
# Getting an intervall of values
print(m[:, 2:])
print(m[:, :2])

tensor(7.)
tensor([3., 7.])
tensor([5., 6., 7., 8.])
tensor([[3., 4.],
        [7., 8.]])
tensor([[1., 2.],
        [5., 6.]])


In [13]:
# like with vectors you can
# Sum (or subtraction)
b = torch.randn(2,4)
print(m + b)
# Multiplication (or division)
print(m * b)

tensor([[0.8395, 1.2557, 3.4256, 4.6629],
        [4.7331, 7.5929, 6.3049, 7.5067]])
tensor([[-0.1605, -1.4885,  1.2769,  2.6517],
        [-1.3345,  9.5575, -4.8660, -3.9460]])


In [14]:
# Transpose a matrix
print(m.t())

tensor([[1., 5.],
        [2., 6.],
        [3., 7.],
        [4., 8.]])


In [15]:
# Flatten a tensor maintaining the same batch size (the first element of the Tensor)
m_4_dim = torch.randn(4,8,2,2)
print(m_4_dim.view(m_4_dim.size(0), -1).size()) 
# Rearrange dimensions
print(m_4_dim.view(m_4_dim.size(0), 16, 2).size()) 

torch.Size([4, 32])
torch.Size([4, 16, 2])


Moving tensors to GPU

In [16]:
# Move tensor to GPU device 0 if there is one (first GPU in the system)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
m_d = m.to(device)
print(m_d.device)

cuda:0


Moving tensors to Numpy

In [17]:
# Converts tensor to numpy array
m_np = m.numpy()
print(m_np)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Tensors concatenations

In [18]:
a = torch.Tensor([[1, 2, 3, 4]])
b = torch.Tensor([[5, 6, 7, 8]])

# Concatenate on axis 0
print(torch.cat((a, b), 0))
# Concatenate on axis 1
print(torch.cat((a, b), 1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])


In [19]:
# Adding and removing dimensions from Tensor
r_t = torch.randn(3,64,64)

# add a dimension
r_t = r_t.unsqueeze(0) # argument is WHERE we want the dimension to be added
print(r_t.size())

# remove a dimension
r_t = r_t.squeeze(0) # argument is WHERE we want the dimension to be removed
print(r_t.size())

torch.Size([1, 3, 64, 64])
torch.Size([3, 64, 64])


In [20]:
# Ex1: Split a 3 dimentional tensors of dimension 4x64x128 
# into 2 tensors of size 4x32x128
# and then concatenate them toghether to get the original size back

In [21]:
# Ex2: You have two matrices of dimension: 4x256x4 and 4x16x64 
# concatenate them toghether to form a single matrix
# of dimension 4x64x32

In [22]:
# Ex3: You have 4 matrixes representing 4 RGB images of dimension 3x128x128.
# Create a grid of dimension 3x256x256